spring.application.name=RecyclingService
spring.datasource.url=jdbc:postgresql://localhost:5432/recycling_db
spring.datasource.username=postgres
spring.datasource.password=admn-eyi164
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true